### ISSUE TITLE
TypeError on simultaneous fetch/read

### ISSUE THREAD

**Issue by ObieMunoz** [ObieMunoz/adventPuzzler#1]
In scenarios where the following lines of code are run concurrently **AND** the datafile for the YEAR/DAY requested has not been previously created and saved to the local directory:

```
let input = adventPuzzler.getPuzzleInput(YEAR, DAY);
input = adventPuzzler.convertInputToArray(input);
```
Will result in the following module error:

```
*/aoc-module/adventPuzzler.js:90
  const array = input.split("\n");
                      ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Object.convertInputToArray (*/aoc-module/adventPuzzler.js:90:23)
    at Object.<anonymous> (*/aoc-module/2021-12-03.js:5:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by ObieMunoz** [comment]
Functions turned async to resolve this error.

resolved in commit 3265b8091c08a2fa509042831e8f24b1bcde0855
